backend:
  name: github
  repo: TwanRieksens/Leonard-Rieksen-Fotografie
  branch: main
  auth_type: implicit
  app_id: YOUR_CLIENT_ID
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: gallery
    label: Gallery
    files:
      - file: "data/gallery.json"
        name: gallery
        label: Gallery
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Category", name: "category", widget: "string"}
          - {label: "Image", name: "image", widget: "string"}
